-- Portfolio CMS Supabase reset + setup
-- Run this whole script in the Supabase SQL Editor.
-- It recreates the expected table, storage bucket, and public policies.
-- Important: this is a public CMS setup. Anyone who can access admin.html can add/delete projects.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text not null,
  project_link text,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;

drop policy if exists "Anyone can read projects" on public.projects;
drop policy if exists "Anyone can add projects" on public.projects;
drop policy if exists "Anyone can delete projects" on public.projects;
drop policy if exists "Public can read projects" on public.projects;
drop policy if exists "Public can add projects" on public.projects;
drop policy if exists "Public can delete projects" on public.projects;

create policy "Anyone can read projects"
on public.projects
for select
to public
using (true);

create policy "Anyone can add projects"
on public.projects
for insert
to public
with check (true);

create policy "Anyone can delete projects"
on public.projects
for delete
to public
using (true);

insert into storage.buckets (id, name, public)
values ('project-images', 'project-images', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

drop policy if exists "Anyone can view project images" on storage.objects;
drop policy if exists "Anyone can upload project images" on storage.objects;
drop policy if exists "Anyone can delete project images" on storage.objects;
drop policy if exists "Public can view project images" on storage.objects;
drop policy if exists "Public can upload project images" on storage.objects;
drop policy if exists "Public can delete project images" on storage.objects;

create policy "Anyone can view project images"
on storage.objects
for select
to public
using (bucket_id = 'project-images');

create policy "Anyone can upload project images"
on storage.objects
for insert
to public
with check (bucket_id = 'project-images');

create policy "Anyone can delete project images"
on storage.objects
for delete
to public
using (bucket_id = 'project-images');
